# Generated by Django 3.1.2 on 2020-11-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='temUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('tem_file', models.FileField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('r_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_title', models.CharField(max_length=100, null=True)),
                ('u_date', models.DateTimeField(auto_now_add=True)),
                ('u_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddp.files')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=100, null=True)),
                ('s_date', models.DateTimeField(auto_now_add=True)),
                ('s_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddp.files')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddp.user')),
                ('shared_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_shared_to', to='ddp.user')),
            ],
        ),
    ]
