# Generated by Django 3.1.2 on 2020-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='u_title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
